@TITLE FNaF Events
@ECHO OFF
SET CNT=1
SET CHICA=0
SET BONNIE=0

ECHO.MO: %CHICA% CHICA
ECHO.MO: %BONNIE% BONNIE

BREAK>MOVEMENTS.cmd

:TIMER
TITLE FNaF Events - TIME: %CNT%

SET /A S_CALC=CNT%%5

SET STATES=
SET /P STATES=<office_states

:: Movement Calculations
IF %S_CALC% EQU 0 (
	SETLOCAL ENABLEDELAYEDEXPANSION
	IF %CNT% GEQ 60 (
		SET /A "RND_CHICA=%RANDOM% %% 100 + 1"
		IF !RND_CHICA! LEQ 20 (
			ENDLOCAL
			SET /A CHICA+=1
			IF %CHICA% GEQ 5 (ECHO.%STATES% | findstr /C:"doorR") >NUL && SET CHICA=1
			SETLOCAL ENABLEDELAYEDEXPANSION
			ECHO.MO: !CHICA! CHICA
			>refresh SET /P "=" <NUL
		)
	)
	IF %CNT% GEQ 25 (
		SET /A "RND_BONNIE=%RANDOM% %% 100 + 1"
		IF !RND_BONNIE! LEQ 20 (
			ENDLOCAL
			SET /A BONNIE+=1
			IF %BONNIE% GEQ 5 (ECHO.%STATES% | findstr /C:"doorL") >NUL && SET BONNIE=1
			SETLOCAL ENABLEDELAYEDEXPANSION
			ECHO.MO: !BONNIE! BONNIE
			>refresh SET /P "=" <NUL
		)
	)
	(
		ECHO.SET CHICA=!CHICA!
		ECHO.SET BONNIE=!BONNIE!
	) >MOVEMENTS.cmd
	ENDLOCAL
)

:FORCE_REFRESH
IF EXIST .\refresh (
	TASKKILL /IM xcopy.exe /F && DEL /Q .\refresh || GOTO :FORCE_REFRESH
)

IF %CNT% EQU 360 (
	TASKKILL /IM xcopy.exe /F
	EXIT
)

SET /A CNT+=1
TIMEOUT /T 1 >NUL
GOTO :TIMER
